drop database inventario;
create database if not exists inventario;
use inventario;

CREATE TABLE USUARIO(
Usuario VARCHAR(30) NOT NULL,
Contrasena TEXT NOT NULL,
NombreCompleto VARCHAR(200) NOT NULL,
Dpi VARCHAR(13) UNIQUE NOT NULL,
AreaTrabajo VARCHAR(100) NOT NULL,
TipoUsuario INT(1) NOT NULL,
Estado INT(1) NOT NULL,
FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FechaEditado TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
CONSTRAINT PK_USUARIO PRIMARY KEY(Usuario)
);

INSERT INTO USUARIO VALUES('admin','0192023a7bbd73250516f069df18b500','Administrador','1234567890123','Administracion',1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


CREATE TABLE PERSONAL(
NoPersonal VARCHAR(50) NOT NULL,
NombreCompleto VARCHAR(200) NOT NULL,
FechaNacimiento DATE NOT NULL,
CorreoElectronico VARCHAR(200) NOT NULL,
Dpi VARCHAR(13) UNIQUE NOT NULL,
Puesto VARCHAR(50) NOT NULL,
Estado INT(1) NOT NULL,
AreaTrabajo VARCHAR(200) NOT NULL,
FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FechaEditado TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
CONSTRAINT PK_PERSONAL PRIMARY KEY(NoPersonal)
);

INSERT INTO PERSONAL(NOPERSONAL,NOMBRECOMPLETO,FECHANACIMIENTO,CORREOELECTRONICO,DPI,PUESTO,ESTADO,AREATRABAJO) VALUES ('0','INVENTARIO','2000-01-01','A@INVENTARIO.COM','0000000000000','INVENTARIO',1,'INVENTARIO');




CREATE TABLE PROVEEDOR(
Nit INT(8) NOT NULL,
Nombre VARCHAR(100) NOT NULL,
Direccion VARCHAR(120) NOT NULL,
AreaTrabajo VARCHAR(100) NOT NULL,
Telefono INT(8) NOT NULL,
FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FechaEditado TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
CONSTRAINT PK_PROVEEDOR PRIMARY KEY(Nit)
);

INSERT INTO PROVEEDOR(NIT,NOMBRE,DIRECCION,AREATRABAJO,TELEFONO) VALUES (00000000,'TRASLADO','TRASLADO','TRASLADO','1234');
INSERT INTO PROVEEDOR(NIT,NOMBRE,DIRECCION,AREATRABAJO,TELEFONO) VALUES (10000000,'DONACION','DONACION','DONACION','5678');

CREATE TABLE TIPOBIEN(
Codigo VARCHAR(30) NOT NULL,
Nombre VARCHAR(200) NOT NULL,
CONSTRAINT PK_TIPO_BIEN PRIMARY KEY(Codigo)
);




CREATE TABLE BIEN(
NoInventario VARCHAR(50) NOT NULL,
Usuario VARCHAR(30) NOT NULL,
NoTarjeta VARCHAR(50) NOT NULL,
UnidadAcademica VARCHAR(30) NOT NULL,
Letra VARCHAR(3) NOT NULL,
NumeroElemento INT NOT NULL,
AnioIngreso INT(4) NOT NULL,
TipoBien VARCHAR(30) NOT NULL,
Descripcion TEXT NULL,
NoFactura VARCHAR(20)  NULL,
FechaFactura DATE  NULL,
FechaIngreso TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FechaEditado TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
NoSolicitudCompra VARCHAR(50)  NULL,
NoOrdenCompra VARCHAR(50)  NULL,
NoCUR VARCHAR(50) NOT NULL,
ValorBien  FLOAT NOT NULL,
Division VARCHAR(50) NOT NULL,
EncargadoInicial VARCHAR(50) NOT NULL,
EncargadoActual VARCHAR(50) NOT NULL,
TipoIngreso ENUM('COMPRA','TRASLADO','DONACION') NOT NULL,
EntidadCompra ENUM('CUNOC','TESORERIA USAC','GUATECOMPRAS') NULL,
EstadoActual INT(1) NOT NULL,
Proveedor INT(8) NOT NULL,
Procedencia VARCHAR(20)  NULL,
NoTranscripcion VARCHAR(20)  NULL,
CorrelativoInscripcion VARCHAR(20) NULL,
NumeroActa VARCHAR(20)  NULL,



CONSTRAINT PK_BIEN PRIMARY KEY(NoInventario),
CONSTRAINT FK_USUARIO_IN_BIEN FOREIGN KEY(Usuario) REFERENCES USUARIO(Usuario),
CONSTRAINT FK_INICIAL_IN_BIEN FOREIGN KEY(EncargadoInicial) REFERENCES PERSONAL(NoPersonal),
CONSTRAINT FK_ACTUAL_IN_BIEN FOREIGN KEY(EncargadoActual) REFERENCES PERSONAL(NoPersonal),
CONSTRAINT FK_PROVEEDOR_IN_BIEN FOREIGN KEY(Proveedor) REFERENCES PROVEEDOR(Nit),
CONSTRAINT FK_TIPOBIEN_IN_BIEN FOREIGN KEY(TipoBien) REFERENCES TIPOBIEN(Codigo)
);


CREATE TABLE TRASLADO(
Id INT AUTO_INCREMENT NOT NULL,
NoInventario VARCHAR(50) NOT NULL,
NoTarjeta VARCHAR(30) NOT NULL,
ResponsableNuevo VARCHAR(50) NOT NULL,
ResponsableAnterior VARCHAR(50) NOT NULL,
FechaTraslado TIMESTAMP NOT NULL,
MotivoTraslado TEXT NOT NULL,
Division VARCHAR(50) NOT NULL,
CONSTRAINT PK_TRASLADO PRIMARY KEY(Id),
CONSTRAINT FK_BIEN_IN_TRASLADO FOREIGN KEY(NoInventario) REFERENCES BIEN(NoInventario),
CONSTRAINT FK_NUEVO_IN_TRASLADO FOREIGN KEY(ResponsableNuevo) REFERENCES PERSONAL(NoPersonal),
CONSTRAINT FK_ANTERIOR_IN_TRASLADO FOREIGN KEY(ResponsableAnterior) REFERENCES PERSONAL(NoPersonal)
);

CREATE TABLE BAJABIEN(
Id INT AUTO_INCREMENT NOT NULL,
NoInventario VARCHAR(50) UNIQUE NOT NULL,
NoAcuerdoConsejo VARCHAR(30) NOT NULL,
NoReferenciaAuditoria VARCHAR(30) NOT NULL,
FechaBaja TIMESTAMP NOT NULL,
CONSTRAINT PK_BAJA PRIMARY KEY(Id),
CONSTRAINT FK_BIEN_IN_BAJA FOREIGN KEY(NoInventario) REFERENCES BIEN(NoInventario)
);







